Four most necessary libraries for Data Science in Python:
    1. Numpy       [package used to create,access,manipulate numpy arrays]
    2. Pandas      [package used to create,access,manipulate dataframe object]
    3. Matlplotlib [package used for visualization]
    4. sk_learn    [package used to implement machine learning model training,testing]

### 1.Numpy ####
#### 1.1 Create numpy array ####

List Recap:
1. Collection of values
2. Hold different data types
3. Add/Remove/Manipulate values of elements

While all above is fine, for data science we need to do mathematical operations over a collections of values faster!
Hence, numpy arrays. Numpy arrays are very similar to lists, but the major difference is numpy arrays can hold values of only one data type. The other differences are:
1. Numpy arrays can do faster calculations
2. List wise calculations

In [3]:
Item_MRP    = [230,3000,64,850,97,1600]
Item_weight = [100,500,50,250,50,500]
print(Item_MRP)

[230, 3000, 64, 850, 97, 1600]


In [4]:
####EXERCISE####
####1.Calculate price unit gram of an item####
####2.Assign it to variable: "Item_punitg"         #####
#Item_punitg = Item_MRP/Item_weight
Item_MRP**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

List does not support many mathematical calculations! Solution : Numpy arrays!

In [5]:
import numpy as np
#Creating Numpy arrays#
np_Item_MRP = np.array(Item_MRP)
print(np_Item_MRP)
print(type(np_Item_MRP))

[ 230 3000   64  850   97 1600]
<class 'numpy.ndarray'>


In [6]:
####Exercise#####
####1.Create array for Item_Weight####
np_Item_weight=np.array(Item_weight)
####2.Array name should be np_Item_Weight####
####3.Print the type of the variable####
print(type(np_Item_weight))

<class 'numpy.ndarray'>


In [ ]:
####Exercise####
####1.Calculate price unit gram of an item####
####2.Assign it to variable "np_Item_punitg"  and then print it####

As we can see above, numpy does element wise calculations.
Numpy Remarks:
1. Numpy can contain only one data type. Even if you provide different data type, there will be coercion
2. '+' operator will do element wise addition in np arrays

In [7]:
np.array([1,"for",True])

array(['1', 'for', 'True'], dtype='<U11')

In [8]:
#compare list and numpy
p_list  = [1,1,1]
print(p_list + p_list)
np_array= np.array([1,1,1])
print(np_array+np_array)

[1, 1, 1, 1, 1, 1]
[2 2 2]


#### 1.2 Access/Manipulate numpy array ####
Exactly same as subsetting/slicing lists

In [9]:
print(np_Item_MRP)
#Print first Item
print(np_Item_MRP[0])
#print last item
print(np_Item_MRP[-1])
#Slice np_array
print(np_Item_MRP[2:4])

[ 230 3000   64  850   97 1600]
230
1600
[ 64 850]


You can subset numpy array using filtering. You cannot do this in lists

In [10]:
np_Item_MRP > 1000
bool = np_Item_MRP > 1000
print(bool)
np_Item_MRP[bool]


[False  True False False False  True]


array([3000, 1600])

### Review ###
You are an indian salesman importing chocolates from US. The price of these chocolates are available in choc_MRP list.But this price is in USD. Calculate and print the price of these chocolates in INR(Assume an 1USD=70INR)

In [11]:
choc_MRP = [6,12,5,8,10,13]
####Write your code below####
np_choc_MRP=np.array(choc_MRP)
np_choc_MRP_new = np_choc_MRP * 70
print(np_choc_MRP_new)

[420 840 350 560 700 910]


Some chocolates are really expensive! Find out which chocolates are expensive(>500 INR) and print their prices in INR

In [12]:
####Write your code below####
bool=np_choc_MRP_new > 500
print(bool)
np_choc_MRP_new[bool]

[False  True False  True  True  True]


array([840, 560, 700, 910])

#### 1.4 2D Numpy Array ####
You can have multi dimensional arrays similar as well. In the previous examples, we had two numpy arrays:np_Item_MRP and np_Item_weight. We can merge them into one single array

In [42]:
np_Item = np.array([Item_MRP,Item_weight])
print(np_Item)
print(type(np_Item))

[[ 230 3000   64  850   97 1600]
 [ 100  500   50  250   50  500]]
<class 'numpy.ndarray'>


In [43]:
np_Item.shape

(2, 6)

#### 1.5 Subsetting/Slicing Numpy Arrays####
<img src="img/np_2d.jpg">

In [45]:
#print 0th row
np_Item[0]

array([ 230, 3000,   64,  850,   97, 1600])

In [46]:
#print the value at 0th row 3rd column
np_Item[0][3]

850

In [47]:
#Alternatie way
np_Item[0,3]

850

In [49]:
#Slicing rows and columns
np_Item[0,0:2]

array([ 230, 3000])

In [50]:
#Slicing rows and columns
np_Item[:,0:2]

array([[ 230, 3000],
       [ 100,  500]])

In [51]:
#Slicing rows and columns
np_Item[:,:]

array([[ 230, 3000,   64,  850,   97, 1600],
       [ 100,  500,   50,  250,   50,  500]])

In [52]:
#Slicing rows and columns
np_Item[1,:]

array([100, 500,  50, 250,  50, 500])

### Review ###
Earlier you had the chocolate MRP in USD in a list. Now you also have their weights in a list.<br/>
1. Create a 2d array "np_chocolate"
2. Print the type of np_chocolate

In [55]:
choc_MRP = [6,12,5,8,10,13]
choc_weight = [10,50,20,10,250]
####Write your code below####
np_choc=np.array([choc_MRP,choc_weight])

In [13]:
####Exercise####
####1.Print the MRP of 4th chocolate####
np_choc[0][3]
####2.Print the weight of 4th chocolate####
np_choc[1][3]
####3.Print the weight of first three chocolates####
np_choc[1][0:3]
####4.Print the MRP of all those chocolates whose weight is 10####

NameError: name 'np_choc' is not defined

#### 1.8 Numpy Statistics ####
We can calculate descriptive statistics for numpy arrays such as mean,median,min,max,sum,sort etc.

In [59]:
####Mean MRP of all Items###
np.mean(np_Item_MRP)

973.5

In [61]:
np.median(np.array(Item_weight))

175.0

In [62]:
np.std(np_Item_MRP)

1053.7782420098326

In [63]:
np.corrcoef(np_Item_MRP,np.array(Item_weight))

array([[1.        , 0.92027866],
       [0.92027866, 1.        ]])

#### Review ####
You have two numpy arrays for chocolate MRP and weight.
Calculate their descriptive statistic and print it.

In [64]:
np_choc_MRP    = np.array(choc_MRP)
np_choc_weight = np.array(choc_weight)

In [66]:
####Exercise####
####1.Calculate the median MRP of chocolates####
####2. Calculate the mean MRP of chocolate in INR####
####3. Calculate the std of chocolate's weight####
####4.Calculate the mean weight of expensive chocolates####