In [1]:
Item_MRP    = [230,3000,64,850,97,1600]
Item_weight = [100,500,50,250,50,500]

In [5]:
import numpy as np
np_Item_MRP=np.array(Item_MRP)
print(type(np_Item_MRP))

<class 'numpy.ndarray'>


In [6]:
np_Item_MRP > 1000

array([False,  True, False, False, False,  True])

In [10]:
bool=np_Item_MRP > 100

In [11]:
print(bool)

[ True  True False  True False  True]


In [12]:
np_Item_MRP[bool]

array([ 230, 3000,  850, 1600])

In [16]:
choc_MRP = [6,12,5,8,10,13]
np_choc_MRP=np.array(choc_MRP)
np_choc_MRP_new = np_choc_MRP * 70

In [17]:
print(np_choc_MRP_new)

[420 840 350 560 700 910]


In [19]:
bool=np_choc_MRP_new > 500

In [20]:
print(bool)

[False  True False  True  True  True]


In [21]:
np_choc_MRP_new[bool]

array([840, 560, 700, 910])

In [22]:
np_Item = np.array([Item_MRP,Item_weight])
print(np_Item)
print(type(np_Item))

[[ 230 3000   64  850   97 1600]
 [ 100  500   50  250   50  500]]
<class 'numpy.ndarray'>


In [25]:
np_Item.shape

(2, 6)

In [26]:
np_Item[1]

array([100, 500,  50, 250,  50, 500])

In [28]:
np_Item[1][5]

500

In [29]:
np_Item[0,0:2]

array([ 230, 3000])

In [30]:
np_Item[1,4:]

array([ 50, 500])

In [31]:
choc_MRP = [6,12,5,8,10,13]
choc_weight = [10,50,20,10,250]

In [34]:
np_choc=np.array([choc_MRP,choc_weight])

In [36]:
np_choc[0][3]

8

In [37]:
np_choc[1][3]

10

In [41]:
np_choc[1][0:3]

[10, 50, 20]

In [44]:
np_choc == 10

array([False, False])

In [45]:
np_choc_MRP = np.array(choc_MRP)

In [46]:
np_choc_weight = np.array(choc_weight)